### ISSUE TITLE
raise建议用try catch捕获显示异常

### ISSUE THREAD

**Issue by NullYing** [inuyasha2012/answer-sheet-scan#2]
不知道怎么回事就raise太难受了

get_left_right
get_top_bottom
这两个函数也至今不知道干嘛用的

**Comment by inuyasha2012** [comment]
我有空整理整理，这个是草稿版的

**Comment by NullYing** [comment]
因为毕业设计是做这方面的，所以还得拜托你尽快整理一下，谢谢。

**Comment by NullYing** [comment]
https://github.com/NullYing/answer_paper_recognition/blob/master/core/scan.py

优化了一下,应该直接切图比较完美,现在不做这方面的东西了
